var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
var strArr2;
var numArr2;
var boolArr2;
var strNumTuple;
myString = 'Hello';
myNum = 22;
myBool = true;
myVar = 100;
strArr = ['hello', 'world'];
strArr2 = ['wow'];
numArr = [1, 2, 3];
numArr2 = [4, 5, 6];
boolArr = [true, true, false];
boolArr2 = [false, false, false];
strNumTuple = ['hello', 10];
console.log(strNumTuple);
